LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/1T2023.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/2t2023.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/3T2023.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/4T2023.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/1T2024.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/2T2024.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/3T2024.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/Arquivos/4T2024.csv'
INTO TABLE demonstracoes_contabeis
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = REPLACE(NULLIF(@VL_SALDO_INICIAL, ''), ',', '.') + 0,
    VL_SALDO_FINAL = REPLACE(NULLIF(@VL_SALDO_FINAL, ''), ',', '.') + 0;